"""
Strategy Executor - Converts parsed JSON strategies into trading signals.
Bridges the gap between natural language parsing and trade execution.
"""
import logging
import re
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Optional, List, Dict, Any, Union
from uuid import UUID, uuid4

import pandas as pd
import numpy as np

from services.market_data_service import get_market_data_service, MarketDataService

logger = logging.getLogger(__name__)


@dataclass
class TradingSignal:
    """Trading signal generated by strategy evaluation."""
    signal_id: str = field(default_factory=lambda: str(uuid4()))
    strategy_id: str = ""
    symbol: str = ""
    exchange: str = "NSE"
    action: str = "hold"  # buy, sell, hold, close
    quantity: int = 1
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    trailing_stop_loss: Optional[float] = None  # Trailing SL percentage
    trailing_stop_activation: Optional[float] = None  # Activate when profit reaches this %
    confidence: float = 1.0
    reason: str = ""
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    
    def to_dict(self) -> dict:
        return {
            "signal_id": self.signal_id,
            "strategy_id": self.strategy_id,
            "symbol": self.symbol,
            "exchange": self.exchange,
            "action": self.action,
            "quantity": self.quantity,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "trailing_stop_loss": self.trailing_stop_loss,
            "trailing_stop_activation": self.trailing_stop_activation,
            "confidence": self.confidence,
            "reason": self.reason,
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class OHLCV:
    """OHLCV data structure."""
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: int
    
    @classmethod
    def from_dict(cls, data: dict) -> "OHLCV":
        return cls(
            timestamp=data.get("timestamp", datetime.now()),
            open=float(data.get("open", 0)),
            high=float(data.get("high", 0)),
            low=float(data.get("low", 0)),
            close=float(data.get("close", 0)),
            volume=int(data.get("volume", 0)),
        )
    
    def to_dict(self) -> dict:
        return {
            "timestamp": self.timestamp.isoformat(),
            "open": self.open,
            "high": self.high,
            "low": self.low,
            "close": self.close,
            "volume": self.volume,
        }


class IndicatorCalculator:
    """Calculates technical indicators from OHLCV data."""
    
    @staticmethod
    def calculate_rsi(closes: List[float], period: int = 14) -> List[float]:
        """Calculate RSI indicator."""
        if len(closes) < period + 1:
            return [50.0] * len(closes)
        
        deltas = [closes[i] - closes[i-1] for i in range(1, len(closes))]
        gains = [d if d > 0 else 0 for d in deltas]
        losses = [-d if d < 0 else 0 for d in deltas]
        
        rsi = [50.0]  # Neutral start
        
        avg_gain = sum(gains[:period]) / period
        avg_loss = sum(losses[:period]) / period
        
        for i in range(1, len(closes)):
            if i >= period:
                avg_gain = (avg_gain * (period - 1) + gains[i - 1]) / period
                avg_loss = (avg_loss * (period - 1) + losses[i - 1]) / period
            
            if avg_loss == 0:
                rsi.append(100.0)
            else:
                rs = avg_gain / avg_loss
                rsi.append(100 - (100 / (1 + rs)))
        
        return rsi
    
    @staticmethod
    def calculate_ema(closes: List[float], period: int) -> List[float]:
        """Calculate EMA indicator."""
        if len(closes) < period:
            return [closes[0]] * len(closes) if closes else [0.0]
        
        multiplier = 2 / (period + 1)
        ema = [closes[0]]
        
        for i in range(1, len(closes)):
            ema.append((closes[i] - ema[-1]) * multiplier + ema[-1])
        
        return ema
    
    @staticmethod
    def calculate_sma(closes: List[float], period: int) -> List[float]:
        """Calculate SMA indicator."""
        if len(closes) < period:
            return [sum(closes) / len(closes)] * len(closes) if closes else [0.0]
        
        sma = []
        for i in range(len(closes)):
            if i < period - 1:
                sma.append(sum(closes[:i+1]) / (i + 1))
            else:
                sma.append(sum(closes[i-period+1:i+1]) / period)
        
        return sma
    
    @staticmethod
    def calculate_macd(closes: List[float], fast: int = 12, slow: int = 26, signal: int = 9) -> tuple:
        """Calculate MACD indicator."""
        ema_fast = IndicatorCalculator.calculate_ema(closes, fast)
        ema_slow = IndicatorCalculator.calculate_ema(closes, slow)
        
        macd_line = [ema_fast[i] - ema_slow[i] for i in range(len(closes))]
        signal_line = IndicatorCalculator.calculate_ema(macd_line, signal)
        histogram = [macd_line[i] - signal_line[i] for i in range(len(closes))]
        
        return macd_line, signal_line, histogram
    
    @staticmethod
    def calculate_vwap(ohlcv_data: List[OHLCV]) -> List[float]:
        """Calculate VWAP indicator."""
        cumulative_tp_vol = 0
        cumulative_vol = 0
        vwap = []
        
        for bar in ohlcv_data:
            typical_price = (bar.high + bar.low + bar.close) / 3
            cumulative_tp_vol += typical_price * bar.volume
            cumulative_vol += bar.volume
            vwap.append(cumulative_tp_vol / cumulative_vol if cumulative_vol > 0 else 0)
        
        return vwap
    
    @staticmethod
    def calculate_all(ohlcv_data: List[Union[OHLCV, dict]], periods: Dict[str, int] = None) -> Dict[str, List[float]]:
        """Calculate all indicators needed for a strategy."""
        if not ohlcv_data:
            return {}
        
        if isinstance(ohlcv_data[0], dict):
            ohlcv_data = [OHLCV.from_dict(d) for d in ohlcv_data]
        
        closes = [bar.close for bar in ohlcv_data]
        highs = [bar.high for bar in ohlcv_data]
        lows = [bar.low for bar in ohlcv_data]
        
        if periods is None:
            periods = {"rsi": 14, "ema_fast": 12, "ema_slow": 26, "macd_signal": 9}
        
        indicators = {
            "close": closes,
            "high": highs,
            "low": lows,
            "rsi": IndicatorCalculator.calculate_rsi(closes, periods.get("rsi", 14)),
            f"ema_{periods.get('ema_fast', 12)}": IndicatorCalculator.calculate_ema(closes, periods.get("ema_fast", 12)),
            f"ema_{periods.get('ema_slow', 26)}": IndicatorCalculator.calculate_ema(closes, periods.get("ema_slow", 26)),
            "vwap": IndicatorCalculator.calculate_vwap(ohlcv_data),
        }
        
        macd_line, signal_line, histogram = IndicatorCalculator.calculate_macd(
            closes, periods.get("ema_fast", 12), periods.get("ema_slow", 26), periods.get("macd_signal", 9)
        )
        indicators["macd"] = macd_line
        indicators["macd_signal"] = signal_line
        indicators["macd_histogram"] = histogram
        
        for p in [9, 21, 50, 100, 200]:
            indicators[f"ema_{p}"] = IndicatorCalculator.calculate_ema(closes, p)
            indicators[f"sma_{p}"] = IndicatorCalculator.calculate_sma(closes, p)
        
        return indicators


class ConditionEvaluator:
    """Evaluates trading conditions from parsed strategy JSON."""
    
    def __init__(self, indicators: Dict[str, List[float]], current_price: float, prev_price: float = None):
        self.indicators = indicators
        self.current_price = current_price
        self.prev_price = prev_price or current_price
    
    def evaluate(self, condition: Union[str, dict]) -> bool:
        """Evaluate a single condition."""
        if isinstance(condition, dict):
            return self._evaluate_dict_condition(condition)
        return self._evaluate_string_condition(str(condition))
    
    def _evaluate_string_condition(self, condition: str) -> bool:
        """Evaluate a string-based condition."""
        condition_lower = condition.lower()
        
        # RSI conditions
        if "rsi" in condition_lower:
            return self._evaluate_rsi_condition(condition_lower)
        
        # EMA conditions
        if "ema" in condition_lower:
            return self._evaluate_ema_condition(condition_lower)
        
        # SMA conditions
        if "sma" in condition_lower:
            return self._evaluate_sma_condition(condition_lower)
        
        # VWAP conditions
        if "vwap" in condition_lower:
            return self._evaluate_vwap_condition(condition_lower)
        
        # MACD conditions
        if "macd" in condition_lower:
            return self._evaluate_macd_condition(condition_lower)
        
        # Volume conditions
        if "volume" in condition_lower:
            return self._evaluate_volume_condition(condition_lower)
        
        # Price conditions
        if "price" in condition_lower:
            return self._evaluate_price_condition(condition_lower)
        
        return False
    
    def _evaluate_dict_condition(self, condition: dict) -> bool:
        """Evaluate a dictionary-based condition."""
        indicator = condition.get("indicator", "").lower()
        operator = condition.get("operator", "")
        value = condition.get("value")
        period = condition.get("period")
        period2 = condition.get("period2")
        
        ind_values = self.indicators
        
        # Get indicator values
        if indicator in ["rsi"]:
            values = ind_values.get("rsi", [50])
        elif "ema" in indicator:
            if period:
                values = ind_values.get(f"ema_{period}", ind_values.get("ema_12", [0]))
            else:
                values = ind_values.get("ema_12", [0])
        elif "sma" in indicator:
            if period:
                values = ind_values.get(f"sma_{period}", ind_values.get("sma_20", [0]))
            else:
                values = ind_values.get("sma_20", [0])
        elif indicator == "vwap":
            values = ind_values.get("vwap", [0])
        elif indicator == "macd":
            values = ind_values.get("macd", [0])
        else:
            values = [self.current_price]
        
        if not values or len(values) < 2:
            return False
        
        current = values[-1]
        previous = values[-2]
        
        if operator == "crosses_above":
            if value is not None:
                return previous < value and current >= value
            if period2:
                other_values = ind_values.get(f"ema_{period2}", [0])
                if len(other_values) >= 2:
                    return previous <= other_values[-2] and current > other_values[-1]
        
        elif operator == "crosses_below":
            if value is not None:
                return previous > value and current <= value
            if period2:
                other_values = ind_values.get(f"ema_{period2}", [0])
                if len(other_values) >= 2:
                    return previous >= other_values[-2] and current < other_values[-1]
        
        elif operator == "greater_than":
            if value is not None:
                return current > value
            if period2:
                other_values = ind_values.get(f"ema_{period2}", [0])
                return current > other_values[-1] if other_values else False
        
        elif operator == "less_than":
            if value is not None:
                return current < value
            if period2:
                other_values = ind_values.get(f"ema_{period2}", [0])
                return current < other_values[-1] if other_values else False
        
        return False
    
    def _evaluate_rsi_condition(self, condition: str) -> bool:
        """Evaluate RSI condition."""
        rsi_values = self.indicators.get("rsi", [50])
        if len(rsi_values) < 2:
            return False
        
        current_rsi = rsi_values[-1]
        prev_rsi = rsi_values[-2]
        
        threshold = self._extract_number(condition)
        
        if "crosses above" in condition:
            return prev_rsi < threshold and current_rsi >= threshold
        elif "crosses below" in condition:
            return prev_rsi > threshold and current_rsi <= threshold
        elif ">" in condition or "above" in condition or "greater" in condition:
            return current_rsi > threshold
        elif "<" in condition or "below" in condition or "less" in condition:
            return current_rsi < threshold
        
        return False
    
    def _evaluate_ema_condition(self, condition: str) -> bool:
        """Evaluate EMA condition."""
        periods = re.findall(r'\d+', condition)
        
        if not periods:
            return False
        
        period = int(periods[0])
        ema_values = self.indicators.get(f"ema_{period}", [0])
        
        if len(ema_values) < 2:
            return False
        
        current_ema = ema_values[-1]
        prev_ema = ema_values[-2]
        current_price = self.current_price
        prev_price = self.prev_price
        
        # Check for EMA crossover
        if "crosses above" in condition:
            if len(periods) > 1:
                period2 = int(periods[1])
                ema2_values = self.indicators.get(f"ema_{period2}", [0])
                if len(ema2_values) >= 2:
                    return prev_ema <= prev_ema and current_ema > ema2_values[-1]
            return prev_price <= prev_ema and current_price > current_ema
        
        elif "crosses below" in condition:
            if len(periods) > 1:
                period2 = int(periods[1])
                ema2_values = self.indicators.get(f"ema_{period2}", [0])
                if len(ema2_values) >= 2:
                    return prev_ema >= ema2_values[-2] and current_ema < ema2_values[-1]
            return prev_price >= prev_ema and current_price < current_ema
        
        elif "above" in condition or ">" in condition:
            if len(periods) > 1:
                period2 = int(periods[1])
                ema2_values = self.indicators.get(f"ema_{period2}", [0])
                return current_ema > ema2_values[-1] if ema2_values else False
            return current_price > current_ema
        
        elif "below" in condition or "<" in condition:
            if len(periods) > 1:
                period2 = int(periods[1])
                ema2_values = self.indicators.get(f"ema_{period2}", [0])
                return current_ema < ema2_values[-1] if ema2_values else False
            return current_price < current_ema
        
        return False
    
    def _evaluate_sma_condition(self, condition: str) -> bool:
        """Evaluate SMA condition."""
        periods = re.findall(r'\d+', condition)
        
        if not periods:
            return False
        
        period = int(periods[0])
        sma_values = self.indicators.get(f"sma_{period}", [0])
        
        if len(sma_values) < 2:
            return False
        
        current_sma = sma_values[-1]
        
        if len(periods) > 1:
            period2 = int(periods[1])
            sma2_values = self.indicators.get(f"sma_{period2}", [0])
            if sma2_values:
                if "above" in condition or ">" in condition:
                    return current_sma > sma2_values[-1]
                elif "below" in condition or "<" in condition:
                    return current_sma < sma2_values[-1]
        
        return False
    
    def _evaluate_vwap_condition(self, condition: str) -> bool:
        """Evaluate VWAP condition."""
        vwap_values = self.indicators.get("vwap", [0])
        
        if not vwap_values:
            return False
        
        current_vwap = vwap_values[-1]
        
        if "above" in condition or "crosses above" in condition:
            return self.current_price > current_vwap
        elif "below" in condition or "crosses below" in condition:
            return self.current_price < current_vwap
        
        return False
    
    def _evaluate_macd_condition(self, condition: str) -> bool:
        """Evaluate MACD condition."""
        macd_values = self.indicators.get("macd", [0])
        signal_values = self.indicators.get("macd_signal", [0])
        
        if len(macd_values) < 2 or len(signal_values) < 2:
            return False
        
        current_macd = macd_values[-1]
        prev_macd = macd_values[-2]
        current_signal = signal_values[-1]
        prev_signal = signal_values[-2]
        
        if "bullish" in condition or "crosses above" in condition:
            return prev_macd <= prev_signal and current_macd > current_signal
        elif "bearish" in condition or "crosses below" in condition:
            return prev_macd >= prev_signal and current_macd < current_signal
        
        return False
    
    def _evaluate_volume_condition(self, condition: str) -> bool:
        """Evaluate Volume condition."""
        if len(self.indicators.get("close", [])) < 2:
            return False
        
        return True  # Simplified - would need volume data
    
    def _evaluate_price_condition(self, condition: str) -> bool:
        """Evaluate Price condition."""
        if "crosses above" in condition:
            return self.prev_price <= self.indicators.get("vwap", [self.prev_price])[-1] and self.current_price > self.indicators.get("vwap", [self.current_price])[-1]
        elif "crosses below" in condition:
            return self.prev_price >= self.indicators.get("vwap", [self.prev_price])[-1] and self.current_price < self.indicators.get("vwap", [self.current_price])[-1]
        
        return False
    
    def _extract_number(self, text: str) -> float:
        """Extract a number from text."""
        match = re.search(r'(\d+(?:\.\d+)?)', text)
        return float(match.group(1)) if match else 0


class StrategyExecutor:
    """
    Main executor that converts parsed strategy JSON into trading signals.
    This is the bridge between natural language parsing and trade execution.
    """
    
    def __init__(self, market_service: MarketDataService = None):
        self.market_service = market_service or get_market_data_service()
        self.indicator_calc = IndicatorCalculator()
    
    async def generate_signal(
        self,
        parsed_strategy: dict,
        symbol: str,
        exchange: str = "NSE",
        timeframe: str = "5min",
        lookback_bars: int = 100,
    ) -> Optional[TradingSignal]:
        """
        Generate a trading signal for a symbol based on parsed strategy.
        
        Args:
            parsed_strategy: Parsed strategy JSON from improved_parser
            symbol: Trading symbol (e.g., "NIFTY")
            exchange: Exchange (e.g., "NSE")
            timeframe: Candle timeframe
            lookback_bars: Number of historical bars to fetch
        
        Returns:
            TradingSignal if conditions are met, None otherwise
        """
        try:
            ohlcv_data = await self._fetch_ohlcv(symbol, exchange, timeframe, lookback_bars)
            
            if not ohlcv_data or len(ohlcv_data) < 20:
                logger.warning(f"Insufficient data for {symbol}")
                return None
            
            indicators = self.indicator_calc.calculate_all(ohlcv_data)
            
            current_price = ohlcv_data[-1].close
            prev_price = ohlcv_data[-2].close if len(ohlcv_data) > 1 else current_price
            
            evaluator = ConditionEvaluator(indicators, current_price, prev_price)
            
            signal = self._evaluate_conditions(
                parsed_strategy, indicators, current_price, symbol, exchange
            )
            
            return signal
            
        except Exception as e:
            logger.error(f"Error generating signal for {symbol}: {e}")
            return None
    
    async def _fetch_ohlcv(
        self,
        symbol: str,
        exchange: str,
        timeframe: str,
        lookback_bars: int
    ) -> List[OHLCV]:
        """Fetch OHLCV data from market service."""
        try:
            interval_map = {
                "1m": "1minute", "5m": "5minute", "15m": "15minute",
                "30m": "30minute", "1h": "1hour", "4h": "4hour",
                "1d": "1day", "daily": "1day"
            }
            interval = interval_map.get(timeframe, "5minute")
            
            to_date = datetime.now(timezone.utc)
            from_date = to_date - timedelta(days=lookback_bars * 2)
            
            ohlcv = await self.market_service.get_ohlcv(
                symbol=symbol,
                exchange=exchange,
                interval=interval,
                from_date=from_date,
                to_date=to_date,
            )
            
            return [OHLCV.from_dict(bar) for bar in ohlcv]
            
        except Exception as e:
            logger.error(f"Error fetching OHLCV: {e}")
            return []
    
    def _evaluate_conditions(
        self,
        strategy: dict,
        indicators: Dict[str, List[float]],
        current_price: float,
        symbol: str,
        exchange: str,
    ) -> Optional[TradingSignal]:
        """Evaluate entry and exit conditions."""
        position = strategy.get("position", "BUY").upper()
        
        entry = strategy.get("entry", [])
        if isinstance(entry, str):
            entry = [entry]
        
        exit_conditions = strategy.get("exit", {})
        
        if not entry:
            return None
        
        entry_conditions_met = all(
            self._check_single_condition(cond, indicators, current_price)
            for cond in entry
        )
        
        if entry_conditions_met:
            signal = TradingSignal(
                strategy_id=strategy.get("strategy_name", "unknown"),
                symbol=symbol,
                exchange=exchange,
                action=position.lower(),
                quantity=1,
                entry_price=current_price,
                confidence=0.8,
                reason=f"Entry conditions met: {', '.join(str(e) for e in entry)}",
            )
            
            if isinstance(exit_conditions, dict):
                if "stoploss" in exit_conditions:
                    sl_value = self._parse_percentage(exit_conditions["stoploss"])
                    if sl_value:
                        signal.stop_loss = current_price * (1 - sl_value / 100) if position == "BUY" else current_price * (1 + sl_value / 100)
                
                if "target" in exit_conditions:
                    tp_value = self._parse_percentage(exit_conditions["target"])
                    if tp_value:
                        signal.take_profit = current_price * (1 + tp_value / 100) if position == "BUY" else current_price * (1 - tp_value / 100)
            
            return signal
        
        return None
    
    def _check_single_condition(
        self,
        condition: Union[str, dict],
        indicators: Dict[str, List[float]],
        current_price: float,
    ) -> bool:
        """Check if a single condition is met."""
        evaluator = ConditionEvaluator(
            indicators,
            current_price,
            indicators.get("close", [current_price])[-2] if len(indicators.get("close", [])) > 1 else current_price
        )
        
        return evaluator.evaluate(condition)
    
    def _parse_percentage(self, value: str) -> Optional[float]:
        """Parse percentage value from string."""
        if isinstance(value, (int, float)):
            return float(value)
        
        match = re.search(r'(\d+(?:\.\d+)?)\s*%', str(value))
        if match:
            return float(match.group(1))
        
        return None
    
    def calculate_position_size(
        self,
        capital: float,
        entry_price: float,
        stop_loss: float,
        risk_percent: float = 1.0,
    ) -> int:
        """Calculate position size based on risk management."""
        risk_amount = capital * (risk_percent / 100)
        
        if stop_loss and stop_loss != entry_price:
            price_risk = abs(entry_price - stop_loss)
            if price_risk > 0:
                return max(1, int(risk_amount / price_risk))
        
        return max(1, int(capital / entry_price))


async def execute_strategy(
    parsed_strategy: dict,
    symbol: str,
    exchange: str = "NSE",
    capital: float = 100000,
    risk_percent: float = 1.0,
) -> Optional[TradingSignal]:
    """
    Convenience function to execute a parsed strategy.
    
    Args:
        parsed_strategy: Strategy JSON from parser
        symbol: Trading symbol
        exchange: Exchange
        capital: Trading capital
        risk_percent: Risk per trade (%)
    
    Returns:
        TradingSignal if conditions met
    """
    executor = StrategyExecutor()
    
    signal = await executor.generate_signal(
        parsed_strategy=parsed_strategy,
        symbol=symbol,
        exchange=exchange,
    )
    
    if signal and signal.action != "hold":
        signal.quantity = executor.calculate_position_size(
            capital=capital,
            entry_price=signal.entry_price or 0,
            stop_loss=signal.stop_loss or 0,
            risk_percent=risk_percent,
        )
    
    return signal
