"""Strategy base class and implementations."""
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any, Optional
import pandas as pd


class StrategyType(str, Enum):
    MOMENTUM = "momentum"
    MEAN_REVERSION = "mean_reversion"
    BREAKOUT = "breakout"
    GRID = "grid"
    DCA = "dca"


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    symbol: str
    action: str  # "buy" or "sell"
    strength: float  # 0 to 1
    price: float
    timestamp: datetime
    metadata: dict


@dataclass
class StrategyConfig:
    """Configuration for a strategy."""
    name: str
    strategy_type: StrategyType
    parameters: dict


class BaseStrategy(ABC):
    """Base class for all trading strategies."""

    def __init__(self, config: StrategyConfig):
        self.config = config
        self.name = config.name
        self.strategy_type = config.strategy_type
        self.params = config.parameters

    @abstractmethod
    def generate_signals(self, data: pd.DataFrame) -> list[Signal]:
        """Generate trading signals from price data."""
        pass

    @abstractmethod
    def validate_parameters(self) -> bool:
        """Validate strategy parameters."""
        pass

    def get_required_parameters(self) -> dict:
        """Return required parameters for this strategy."""
        return {}


class MomentumStrategy(BaseStrategy):
    """Momentum trading strategy - buy when price is trending up."""

    def validate_parameters(self) -> bool:
        required = ["lookback_period", "entry_threshold", "exit_threshold"]
        for param in required:
            if param not in self.params:
                return False
        return True

    def get_required_parameters(self) -> dict:
        return {
            "lookback_period": {"type": "int", "default": 20, "min": 5, "max": 200},
            "entry_threshold": {"type": "float", "default": 0.02, "min": 0.01, "max": 0.1},
            "exit_threshold": {"type": "float", "default": 0.01, "min": 0.005, "max": 0.05},
        }

    def generate_signals(self, data: pd.DataFrame) -> list[Signal]:
        if not self.validate_parameters():
            return []

        lookback = self.params.get("lookback_period", 20)
        entry_thresh = self.params.get("entry_threshold", 0.02)
        exit_thresh = self.params.get("exit_threshold", 0.01)

        if len(data) < lookback:
            return []

        signals = []
        current_price = data.iloc[-1]["close"]
        past_prices = data.iloc[-lookback:-1]["close"]

        momentum = (current_price - past_prices.iloc[0]) / past_prices.iloc[0]

        if momentum > entry_thresh:
            signals.append(Signal(
                symbol=data.iloc[-1].get("symbol", "UNKNOWN"),
                action="buy",
                strength=min(momentum, 1.0),
                price=current_price,
                timestamp=datetime.now(),
                metadata={"momentum": momentum, "strategy": "momentum"}
            ))
        elif momentum < -exit_thresh:
            signals.append(Signal(
                symbol=data.iloc[-1].get("symbol", "UNKNOWN"),
                action="sell",
                strength=min(abs(momentum), 1.0),
                price=current_price,
                timestamp=datetime.now(),
                metadata={"momentum": momentum, "strategy": "momentum"}
            ))

        return signals


class MeanReversionStrategy(BaseStrategy):
    """Mean reversion strategy - buy when price is below average, sell when above."""

    def validate_parameters(self) -> bool:
        required = ["lookback_period", "std_dev_multiplier"]
        for param in required:
            if param not in self.params:
                return False
        return True

    def get_required_parameters(self) -> dict:
        return {
            "lookback_period": {"type": "int", "default": 20, "min": 5, "max": 200},
            "std_dev_multiplier": {"type": "float", "default": 2.0, "min": 1.0, "max": 3.0},
            "exit_threshold": {"type": "float", "default": 0.0, "min": 0.0, "max": 0.5},
        }

    def generate_signals(self, data: pd.DataFrame) -> list[Signal]:
        if not self.validate_parameters():
            return []

        lookback = self.params.get("lookback_period", 20)
        std_mult = self.params.get("std_dev_multiplier", 2.0)
        exit_thresh = self.params.get("exit_threshold", 0.0)

        if len(data) < lookback:
            return []

        signals = []
        current_price = data.iloc[-1]["close"]
        window = data.iloc[-lookback:]["close"]

        mean = window.mean()
        std = window.std()
        z_score = (current_price - mean) / std if std > 0 else 0

        if z_score < -std_mult:
            signals.append(Signal(
                symbol=data.iloc[-1].get("symbol", "UNKNOWN"),
                action="buy",
                strength=min(abs(z_score) / std_mult, 1.0),
                price=current_price,
                timestamp=datetime.now(),
                metadata={"z_score": z_score, "mean": mean, "strategy": "mean_reversion"}
            ))
        elif z_score > std_mult:
            signals.append(Signal(
                symbol=data.iloc[-1].get("symbol", "UNKNOWN"),
                action="sell",
                strength=min(z_score / std_mult, 1.0),
                price=current_price,
                timestamp=datetime.now(),
                metadata={"z_score": z_score, "mean": mean, "strategy": "mean_reversion"}
            ))
        elif abs(z_score) < exit_thresh:
            signals.append(Signal(
                symbol=data.iloc[-1].get("symbol", "UNKNOWN"),
                action="sell",
                strength=0.5,
                price=current_price,
                timestamp=datetime.now(),
                metadata={"z_score": z_score, "reason": "mean_reverted", "strategy": "mean_reversion"}
            ))

        return signals


class BreakoutStrategy(BaseStrategy):
    """Breakout strategy - buy when price breaks resistance, sell on support break."""

    def validate_parameters(self) -> bool:
        required = ["lookback_period", "breakout_threshold"]
        for param in required:
            if param not in self.params:
                return False
        return True

    def get_required_parameters(self) -> dict:
        return {
            "lookback_period": {"type": "int", "default": 20, "min": 5, "max": 100},
            "breakout_threshold": {"type": "float", "default": 0.01, "min": 0.005, "max": 0.05},
        }

    def generate_signals(self, data: pd.DataFrame) -> list[Signal]:
        if not self.validate_parameters():
            return []

        lookback = self.params.get("lookback_period", 20)
        breakout_thresh = self.params.get("breakout_threshold", 0.01)

        if len(data) < lookback:
            return []

        signals = []
        current_price = data.iloc[-1]["close"]
        high = data.iloc[-lookback:-1]["high"].max()
        low = data.iloc[-lookback:-1]["low"].min()

        if current_price > high * (1 + breakout_thresh):
            signals.append(Signal(
                symbol=data.iloc[-1].get("symbol", "UNKNOWN"),
                action="buy",
                strength=0.8,
                price=current_price,
                timestamp=datetime.now(),
                metadata={"resistance": high, "breakout": "up", "strategy": "breakout"}
            ))
        elif current_price < low * (1 - breakout_thresh):
            signals.append(Signal(
                symbol=data.iloc[-1].get("symbol", "UNKNOWN"),
                action="sell",
                strength=0.8,
                price=current_price,
                timestamp=datetime.now(),
                metadata={"support": low, "breakout": "down", "strategy": "breakout"}
            ))

        return signals


class GridStrategy(BaseStrategy):
    """Grid trading strategy - place buy/sell orders at regular intervals."""

    def validate_parameters(self) -> bool:
        required = ["grid_levels", "grid_spacing", "position_size"]
        for param in required:
            if param not in self.params:
                return False
        return True

    def get_required_parameters(self) -> dict:
        return {
            "grid_levels": {"type": "int", "default": 5, "min": 3, "max": 20},
            "grid_spacing": {"type": "float", "default": 0.02, "min": 0.01, "max": 0.1},
            "position_size": {"type": "int", "default": 100, "min": 1, "max": 10000},
        }

    def generate_signals(self, data: pd.DataFrame) -> list[Signal]:
        if not self.validate_parameters():
            return []

        grid_levels = self.params.get("grid_levels", 5)
        grid_spacing = self.params.get("grid_spacing", 0.02)
        position_size = self.params.get("position_size", 100)

        if len(data) < 1:
            return []

        signals = []
        current_price = data.iloc[-1]["close"]

        base_price = current_price * (1 - (grid_levels // 2) * grid_spacing)

        for i in range(grid_levels):
            grid_price = base_price * (1 + i * grid_spacing)
            
            if current_price <= grid_price * (1 + grid_spacing / 2):
                signals.append(Signal(
                    symbol=data.iloc[-1].get("symbol", "UNKNOWN"),
                    action="buy",
                    strength=1.0 - (i / grid_levels),
                    price=grid_price,
                    timestamp=datetime.now(),
                    metadata={"grid_level": i, "strategy": "grid"}
                ))
                break

        return signals


class DCAStrategy(BaseStrategy):
    """Dollar Cost Averaging strategy - buy at regular intervals regardless of price."""

    def validate_parameters(self) -> bool:
        required = ["buy_interval", "buy_amount", "max_position"]
        for param in required:
            if param not in self.params:
                return False
        return True

    def get_required_parameters(self) -> dict:
        return {
            "buy_interval": {"type": "int", "default": 1, "min": 1, "max": 30, "unit": "days"},
            "buy_amount": {"type": "float", "default": 1000, "min": 100, "max": 100000},
            "max_position": {"type": "int", "default": 10000, "min": 1000, "max": 1000000},
            "price_drop_threshold": {"type": "float", "default": 0.05, "min": 0.01, "max": 0.2},
        }

    def generate_signals(self, data: pd.DataFrame) -> list[Signal]:
        if not self.validate_parameters():
            return []

        buy_interval = self.params.get("buy_interval", 1)
        buy_amount = self.params.get("buy_amount", 1000)
        max_position = self.params.get("max_position", 10000)
        price_drop = self.params.get("price_drop_threshold", 0.05)

        if len(data) < 2:
            return []

        signals = []
        current_price = data.iloc[-1]["close"]
        avg_price = data.iloc[:-1]["close"].mean()

        if current_price < avg_price * (1 - price_drop):
            action = "buy"
            strength = min(abs(current_price - avg_price) / avg_price / price_drop, 1.0)
        else:
            return signals

        quantity = int(buy_amount / current_price)
        
        if quantity > 0:
            signals.append(Signal(
                symbol=data.iloc[-1].get("symbol", "UNKNOWN"),
                action=action,
                strength=strength,
                price=current_price,
                timestamp=datetime.now(),
                metadata={
                    "dca_amount": buy_amount,
                    "avg_price": avg_price,
                    "drop_percent": abs(current_price - avg_price) / avg_price,
                    "strategy": "dca"
                }
            ))

        return signals


STRATEGY_MAP = {
    StrategyType.MOMENTUM: MomentumStrategy,
    StrategyType.MEAN_REVERSION: MeanReversionStrategy,
    StrategyType.BREAKOUT: BreakoutStrategy,
    StrategyType.GRID: GridStrategy,
    StrategyType.DCA: DCAStrategy,
}


def get_strategy(strategy_type: StrategyType, config: StrategyConfig) -> BaseStrategy:
    """Get strategy instance by type."""
    strategy_class = STRATEGY_MAP.get(strategy_type)
    if not strategy_class:
        raise ValueError(f"Unknown strategy type: {strategy_type}")
    return strategy_class(config)
